### ISSUE TITLE
License related help

### ISSUE THREAD

**Issue by sandeeptengale** [amay077/android-wheel-datetime-picker#1]
I want to use android wheel datepicker for my project, where I need to modify some styles. I also need to make changes in "wheel" module since it is in old eclipse format project. Since this comes under Apache License 2.0, is it okay to change the project structure and resource file??

**Comment by amay077** [comment]
Sure!
I no longer maintained this repository, nay, I just committed once only.

You can fork this repository and change any resources. (I add [LICENSE](https://github.com/amay077/android-wheel-datetime-picker/blob/master/LICENSE) just now.)
I'd like to merge your pull requests if you send it.
